spring:
  main:
    banner-mode: "off"

server:
  port: 8888

mongodb:
  database: "centrologistico"
  host: "127.0.0.1"
  port: "27017"

security:
  user:
    name: admin
    password: 123456
    role: SYSTEM